version: '3.1'

services:
  otusdb:
    image: mysql:8.0.21
    environment:
      - MYSQL_DATABASE=otus
      - MYSQL_USER=otus
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=secret
#    command:
#      --init-file /init.sql
    volumes:
      - ~/docker/otus/mysql/data:/var/lib/mysql
      #- ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    ports:
      - "33060:3306"
