-- MySQL Script generated by MySQL Workbench
-- Сб 01 авг 2020 14:42:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema x_shop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `x_shop` ;

-- -----------------------------------------------------
-- Schema x_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `x_shop` ;
SHOW WARNINGS;
USE `x_shop` ;

-- -----------------------------------------------------
-- Table `x_shop`.`titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`titles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`titles` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`marital_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`marital_statuses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`marital_statuses` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`languages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`languages` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`genders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`genders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`genders` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`customers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`customers` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `birth_date` DATE NULL,
  `title_id` INT NOT NULL,
  `marital_status_id` INT NULL,
  `correspondence_language_id` INT NOT NULL,
  `gender_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customers_titles`
    FOREIGN KEY (`title_id`)
    REFERENCES `x_shop`.`titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_marital_statuses1`
    FOREIGN KEY (`marital_status_id`)
    REFERENCES `x_shop`.`marital_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_languages1`
    FOREIGN KEY (`correspondence_language_id`)
    REFERENCES `x_shop`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_genders1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `x_shop`.`genders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_customers_titles_idx` ON `x_shop`.`customers` (`title_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_customers_marital_statuses1_idx` ON `x_shop`.`customers` (`marital_status_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_customers_languages1_idx` ON `x_shop`.`customers` (`correspondence_language_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_customers_genders1_idx` ON `x_shop`.`customers` (`gender_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`countries` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`countries` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`regions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`regions` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_regions_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `x_shop`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_regions_countries1_idx` ON `x_shop`.`regions` (`country_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`cities` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`cities` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `country_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cities_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `x_shop`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cities_regions1`
    FOREIGN KEY (`region_id`)
    REFERENCES `x_shop`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_cities_countries1_idx` ON `x_shop`.`cities` (`country_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_cities_regions1_idx` ON `x_shop`.`cities` (`region_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`streets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`streets` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`streets` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_streets_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `x_shop`.`cities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_streets_cities1_idx` ON `x_shop`.`streets` (`city_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`postal_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`postal_codes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`postal_codes` (
  `id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `streets_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_postal_codes_streets1`
    FOREIGN KEY (`streets_id`)
    REFERENCES `x_shop`.`streets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_postal_codes_streets1_idx` ON `x_shop`.`postal_codes` (`streets_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`building_numbers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`building_numbers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`building_numbers` (
  `id` INT NOT NULL,
  `value` VARCHAR(255) NOT NULL,
  `postal_code_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_building_numbers_postal_codes1`
    FOREIGN KEY (`postal_code_id`)
    REFERENCES `x_shop`.`postal_codes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_building_numbers_postal_codes1_idx` ON `x_shop`.`building_numbers` (`postal_code_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`addresses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`addresses` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `building_number_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_addresses_building_numbers1`
    FOREIGN KEY (`building_number_id`)
    REFERENCES `x_shop`.`building_numbers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_addresses_building_numbers1_idx` ON `x_shop`.`addresses` (`building_number_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`customer_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`customer_address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`customer_address` (
  `customer_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`, `address_id`),
  CONSTRAINT `fk_customers_has_addresses_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `x_shop`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_has_addresses_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `x_shop`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_customers_has_addresses_addresses1_idx` ON `x_shop`.`customer_address` (`address_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_customers_has_addresses_customers1_idx` ON `x_shop`.`customer_address` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `parent_id` INT UNSIGNED NULL,
  `lft` INT UNSIGNED NOT NULL,
  `rgt` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categories_categories1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `x_shop`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_categories_categories1_idx` ON `x_shop`.`categories` (`parent_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`order_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`order_statuses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`order_statuses` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`product_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`product_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`product_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`manufacturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`manufacturers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `contacts` JSON NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`vendors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`vendors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`vendors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `contacts` JSON NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `product_type_id` INT NOT NULL,
  `quantity` INT NULL,
  `manufacturer_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_products_product_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `x_shop`.`product_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_manufacturers1`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `x_shop`.`manufacturers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_vendors1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `x_shop`.`vendors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_products_product_types1_idx` ON `x_shop`.`products` (`product_type_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_products_manufacturers1_idx` ON `x_shop`.`products` (`manufacturer_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_products_vendors1_idx` ON `x_shop`.`products` (`vendor_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`order_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`order_products` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`order_products` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `product_id` INT UNSIGNED NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `product_props` JSON NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_order_products_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `x_shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_order_products_products1_idx` ON `x_shop`.`order_products` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`orders` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`orders` (
  `id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `customer_id` INT NOT NULL,
  `order_statuse_id` INT NOT NULL,
  `order_product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `x_shop`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_statuses1`
    FOREIGN KEY (`order_statuse_id`)
    REFERENCES `x_shop`.`order_statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_order_products1`
    FOREIGN KEY (`order_product_id`)
    REFERENCES `x_shop`.`order_products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_orders_customers1_idx` ON `x_shop`.`orders` (`customer_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_orders_order_statuses1_idx` ON `x_shop`.`orders` (`order_statuse_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_orders_order_products1_idx` ON `x_shop`.`orders` (`order_product_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`price_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`price_types` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`price_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`currencies` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`currencies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`price_units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`price_units` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`price_units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`prices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`prices` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`prices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` DECIMAL(10,2) NOT NULL,
  `price_type_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `price_unit_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prices_price_type1`
    FOREIGN KEY (`price_type_id`)
    REFERENCES `x_shop`.`price_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prices_currencies1`
    FOREIGN KEY (`currency_id`)
    REFERENCES `x_shop`.`currencies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prices_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `x_shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prices_price_units1`
    FOREIGN KEY (`price_unit_id`)
    REFERENCES `x_shop`.`price_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_prices_price_type1_idx` ON `x_shop`.`prices` (`price_type_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_prices_currencies1_idx` ON `x_shop`.`prices` (`currency_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_prices_products1_idx` ON `x_shop`.`prices` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_prices_price_units1_idx` ON `x_shop`.`prices` (`price_unit_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`products_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`products_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`products_categories` (
  `product_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  CONSTRAINT `fk_products_has_categories_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `x_shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_categories_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `x_shop`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_products_has_categories_categories1_idx` ON `x_shop`.`products_categories` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`product_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`product_props` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`product_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prop_name` VARCHAR(255) NOT NULL,
  `prop_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`product_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`product_values` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`product_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `int_value` INT NULL,
  `float_value` FLOAT NULL,
  `string_value` VARCHAR(512) NULL,
  `text_value` TEXT NULL,
  ` date_value` DATE NULL,
  `split_value` JSON NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `product_prop_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_product_values_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `x_shop`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_values_product_props1`
    FOREIGN KEY (`product_prop_id`)
    REFERENCES `x_shop`.`product_props` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_product_values_products1_idx` ON `x_shop`.`product_values` (`product_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_product_values_product_props1_idx` ON `x_shop`.`product_values` (`product_prop_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `x_shop`.`product_prop_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `x_shop`.`product_prop_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `x_shop`.`product_prop_type` (
  `product_type_id` INT NOT NULL,
  `product_prop_id` INT NOT NULL,
  PRIMARY KEY (`product_type_id`, `product_prop_id`),
  CONSTRAINT `fk_product_types_has_product_props_product_types1`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `x_shop`.`product_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_types_has_product_props_product_props1`
    FOREIGN KEY (`product_prop_id`)
    REFERENCES `x_shop`.`product_props` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;
CREATE INDEX `fk_product_types_has_product_props_product_props1_idx` ON `x_shop`.`product_prop_type` (`product_prop_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_product_types_has_product_props_product_types1_idx` ON `x_shop`.`product_prop_type` (`product_type_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
